name: Deploy Web Workflow
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build jc-chip8 --release --target=web --no-typescript -d ../examples/web/wasmpack -- --features web
      - run: rm examples/web/wasmpack/.gitignore examples/web/wasmpack/package.json
      - run: cp examples/web/wasmpack/* examples/web
      - run: rm -rf examples/web/wasmpack
      - uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: examples/web
          MESSAGE: "{sha} {msg}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
